name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Download Allure history
      run: |
        mkdir -p allure-results/history
        curl -s "https://b46e-80-238-117-154.ngrok-free.app/allure-docker-service/history?project_id=default" \
          | tar -xz -C allure-results/history || true
    - name: Run Playwright tests
      run: npx playwright test
      env:
        UI_BASE_URL: ${{ secrets.UI_BASE_URL }}
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
    - name: Upload Allure results
      run: |
        curl -X POST "https://b46e-80-238-117-154.ngrok-free.app/allure-docker-service/send-results?project_id=default" \
          -H "Content-Type: multipart/form-data" \
          -F "files[]=@allure-results/*"
    - name: Generate Allure report
      run: |
        curl "https://b46e-80-238-117-154.ngrok-free.app/allure-docker-service/generate-report?project_id=default"
    - name: Print Allure URL
      run: |
        echo "Allure report:"
        echo "https://b46e-80-238-117-154.ngrok-free.app/allure-docker-service/latest-report?project_id=default"
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
